name: car_repository
description: A dart package that manages the car domain
publish_to: 'none'



environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.2'

dependencies:
  equatable: ^2.0.5
  fpdart: ^1.1.0
  json_annotation: ^4.8.1
  car_api:
    path: ../car_api
  errors:
    path: ../errors

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  test: ^1.24.9
