name: car_dealership
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.13.9'

dependencies:
  another_transformer_page_view: ^2.0.1
  authentication_repository:
    path: packages/authentication_repository
  flutter:
    sdk: flutter
  car_repository:
    path: packages/car_repository
  cloud_firestore: ^4.12.2
  errors:
    path: packages/errors
  equatable: ^2.0.5
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3
  firebase_storage: ^11.4.1
  flutter_bloc: ^8.1.3
  formz: ^0.6.1
  formz_input:
    path: packages/formz_input
  gap: ^3.0.1
  go_router: ^12.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  melos: ^3.2.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCerealBlack.ttf
          weight: 900
        - asset: assets/fonts/AirbnbCerealExtraBold.ttf
          weight: 700
        - asset: assets/fonts/AirbnbCerealMedium.ttf
          weight: 600
        - asset: assets/fonts/AirbnbCerealBold.ttf
          weight: 500
        - asset: assets/fonts/AirbnbCerealBook.ttf
          weight: 400
        - asset: assets/fonts/AirbnbCerealLight.ttf
          weight: 300
