name: car_dealership
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  car_repository:
    path: packages/car_repository
  cloud_firestore: ^4.12.2
  equatable: ^2.0.5
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3
  firebase_storage: ^11.4.1
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  melos: ^3.2.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
