// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrr8-prBMAgDONqUZdTw1AV0CV1vCQJ2k',
    appId: '1:438231719501:web:4f84a180050f83d0c48604',
    messagingSenderId: '438231719501',
    projectId: 'kap-car-dealership',
    authDomain: 'kap-car-dealership.firebaseapp.com',
    storageBucket: 'kap-car-dealership.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6VVMBjKoIMbxqQ3j-ur-2AQoI_p7Kc78',
    appId: '1:438231719501:android:9def22a647f16673c48604',
    messagingSenderId: '438231719501',
    projectId: 'kap-car-dealership',
    storageBucket: 'kap-car-dealership.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkd-AXiPLbycIZ1U4BUxVOG-dmOU35qvA',
    appId: '1:438231719501:ios:3e6de6044927c374c48604',
    messagingSenderId: '438231719501',
    projectId: 'kap-car-dealership',
    storageBucket: 'kap-car-dealership.appspot.com',
    iosBundleId: 'com.example.carDealership',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkd-AXiPLbycIZ1U4BUxVOG-dmOU35qvA',
    appId: '1:438231719501:ios:cbc9ee258e0017dfc48604',
    messagingSenderId: '438231719501',
    projectId: 'kap-car-dealership',
    storageBucket: 'kap-car-dealership.appspot.com',
    iosBundleId: 'com.example.carDealership.RunnerTests',
  );
}
